### ISSUE TITLE
Sipariş Zamanlamasında Hata

### ISSUE THREAD

**Issue by fuchstech** [altuntasmuhammet/trendyol-api-python-sdk#2]
import json
from trendyol_sdk.api import TrendyolApiClient
from trendyol_sdk.services  import OrderIntegrationService
import json

api = TrendyolApiClient(api_key="API", api_secret="SECRET", supplier_id="ID")

service = OrderIntegrationService(api)
shipment = service.get_shipment_packages(None)

json_obj = json.dumps(shipment, indent=4, ensure_ascii=False, sort_keys=True)
print(json_obj)

Merhabalar api servisinden gelen verileri başarıyla okuyabiliyorum ancak gelen veriler eski tarihli veriler. En erken bir önceki günün verilerini gösterebiliyor. Gerçek zamanlı olarak veirlere ulaşmam mümkün mü?

**Comment by altuntasmuhammet** [comment]
startDate, endDate parametrelerini girmemeniz halinde varsayılan olarak son bir haftadaki siparişler gösterilecektir. Dolayısıyla bu sorgudan dönen cevabın content bilgisindeki ilk eleman, en güncel siparişin bilgilerini içeriyor olmalı.

**Comment by Passeportout** [comment]
Cevabınız için teşekkür ederim hocam ben problemin print fonksiyonundan kaynaklandığını fark ettim 10000 satırdan fazlasını print etmediği için tüm verileri göstermiyormuş. Json Dosyası olarak kaydedince problem çözüldü.

**Comment by fuchstech** [comment]
Cevabınız için teşekkür ederim hocam ben problemin print fonksiyonundan kaynaklandığını fark ettim 10000 satırdan fazlasını print etmediği için tüm verileri göstermiyormuş. Json Dosyası olarak kaydedince problem çözüldü.
